// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: coord/coord.proto

package coord

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuardAddr string `protobuf:"bytes,1,opt,name=GuardAddr,proto3" json:"GuardAddr,omitempty"`
	RelayAddr string `protobuf:"bytes,2,opt,name=RelayAddr,proto3" json:"RelayAddr,omitempty"`
	ExitAddr  string `protobuf:"bytes,3,opt,name=ExitAddr,proto3" json:"ExitAddr,omitempty"`
}

func (x *Chain) Reset() {
	*x = Chain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_coord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_coord_coord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_coord_coord_proto_rawDescGZIP(), []int{0}
}

func (x *Chain) GetGuardAddr() string {
	if x != nil {
		return x.GuardAddr
	}
	return ""
}

func (x *Chain) GetRelayAddr() string {
	if x != nil {
		return x.RelayAddr
	}
	return ""
}

func (x *Chain) GetExitAddr() string {
	if x != nil {
		return x.ExitAddr
	}
	return ""
}

type NodeJoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListenAddr string `protobuf:"bytes,1,opt,name=ListenAddr,proto3" json:"ListenAddr,omitempty"`
}

func (x *NodeJoinRequest) Reset() {
	*x = NodeJoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_coord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeJoinRequest) ProtoMessage() {}

func (x *NodeJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coord_coord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeJoinRequest.ProtoReflect.Descriptor instead.
func (*NodeJoinRequest) Descriptor() ([]byte, []int) {
	return file_coord_coord_proto_rawDescGZIP(), []int{1}
}

func (x *NodeJoinRequest) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

type NodeJoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role string `protobuf:"bytes,1,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *NodeJoinResponse) Reset() {
	*x = NodeJoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_coord_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeJoinResponse) ProtoMessage() {}

func (x *NodeJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coord_coord_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeJoinResponse.ProtoReflect.Descriptor instead.
func (*NodeJoinResponse) Descriptor() ([]byte, []int) {
	return file_coord_coord_proto_rawDescGZIP(), []int{2}
}

func (x *NodeJoinResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_coord_coord_proto protoreflect.FileDescriptor

var file_coord_coord_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x5f,
	0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x75, 0x61, 0x72, 0x64,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x41, 0x64,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x69, 0x74, 0x41, 0x64, 0x64, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x78, 0x69, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22,
	0x31, 0x0a, 0x0f, 0x4e, 0x6f, 0x64, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x41, 0x64,
	0x64, 0x72, 0x22, 0x26, 0x0a, 0x10, 0x4e, 0x6f, 0x64, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x32, 0x8b, 0x01, 0x0a, 0x0c, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x08, 0x4e,
	0x6f, 0x64, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x4e,
	0x6f, 0x64, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x12, 0x10, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x4e, 0x6f, 0x64, 0x65,
	0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x63, 0x73, 0x2e, 0x75,
	0x62, 0x63, 0x2e, 0x63, 0x61, 0x2f, 0x63, 0x70, 0x73, 0x63, 0x34, 0x31, 0x36, 0x2f, 0x6f, 0x6e,
	0x69, 0x6f, 0x6e, 0x52, 0x50, 0x43, 0x2f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coord_coord_proto_rawDescOnce sync.Once
	file_coord_coord_proto_rawDescData = file_coord_coord_proto_rawDesc
)

func file_coord_coord_proto_rawDescGZIP() []byte {
	file_coord_coord_proto_rawDescOnce.Do(func() {
		file_coord_coord_proto_rawDescData = protoimpl.X.CompressGZIP(file_coord_coord_proto_rawDescData)
	})
	return file_coord_coord_proto_rawDescData
}

var file_coord_coord_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_coord_coord_proto_goTypes = []interface{}{
	(*Chain)(nil),            // 0: coordNode.Chain
	(*NodeJoinRequest)(nil),  // 1: coordNode.NodeJoinRequest
	(*NodeJoinResponse)(nil), // 2: coordNode.NodeJoinResponse
}
var file_coord_coord_proto_depIdxs = []int32{
	1, // 0: coordNode.CoordService.NodeJoin:input_type -> coordNode.NodeJoinRequest
	0, // 1: coordNode.CoordService.RequestChain:input_type -> coordNode.Chain
	2, // 2: coordNode.CoordService.NodeJoin:output_type -> coordNode.NodeJoinResponse
	0, // 3: coordNode.CoordService.RequestChain:output_type -> coordNode.Chain
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_coord_coord_proto_init() }
func file_coord_coord_proto_init() {
	if File_coord_coord_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coord_coord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coord_coord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeJoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coord_coord_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeJoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coord_coord_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coord_coord_proto_goTypes,
		DependencyIndexes: file_coord_coord_proto_depIdxs,
		MessageInfos:      file_coord_coord_proto_msgTypes,
	}.Build()
	File_coord_coord_proto = out.File
	file_coord_coord_proto_rawDesc = nil
	file_coord_coord_proto_goTypes = nil
	file_coord_coord_proto_depIdxs = nil
}
